### ISSUE TITLE
devkitPro still distributes v1.04 of gbafix

### ISSUE THREAD

**Issue by tom42** [devkitPro/gba-tools#5]
I just ran the updater. The installed version of gbafix still appears to be 1.04 rather than 1.05 (which has the -d option added).

**Comment by fincs** [comment]
Cannot reproduce. Make sure you have all packages up to date (`(sudo) (dkp-)pacman -Syu`).

**Comment by tom42** [comment]
I'm running Windows 10.

I ran the command you gave me:

```
C:\Users\mathy>pacman -Syu
:: Synchronizing package databases...
 msys is up to date
 dkp-libs is up to date
 dkp-windows is up to date
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
 there is nothing to do
```

Still the same:

```
C:\Users\mathy>c:\devkitPro\devkitARM\bin\gbafix.exe
GBA ROM fixer v1.04 by Dark Fader / BlackThunder / WinterMute
Syntax: gbafix <rom.gba> [-p] [-t[title]] [-g<game_code>] [-m<maker_code>] [-v<version>]

parameters:
        -p              Pad to next exact power of 2. No minimum size!
        -t[<title>]     Patch title. Stripped filename if none given.
        -c<game_code>   Patch game code (four characters)
        -m<maker_code>  Patch maker code (two characters)
        -r<version>     Patch game version (number)
```

**Comment by fincs** [comment]
gbafix.exe is no longer distributed within devkitARM. The executable is now located at devkitPro\tools\bin\gbafix.exe. This tells me that you have had devkitPro products installed for a long time, prior to us introducing pacman.

In this case, I'd be inclined to perform a clean install to clear out any other leftovers.

**Comment by tom42** [comment]
That fixed it. Sorry for the false bug report and thank you for the quick help.
